version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file: .env
    ports:
      - "5000:5000"
    environment:
      API_HOST: "app"
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./src:/src

  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  database:
